name: example
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  rift_flutter:
    path: ..

dependency_overrides:
  rift:
    path: ../../rift

flutter:
  uses-material-design: true

