import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';

part 'rift_schema.g.dart';

/// Information about Rift adapters used to support incremental changes
@JsonSerializable()
@immutable
class RiftSchema {
  /// The comment placed at the top of the schema file
  static const comment = '''
# Generated by Rift CE
# Manual modifications may be necessary for certain migrations
# Check in to version control''';

  /// The next type ID to use for future updates
  final int nextTypeId;

  /// The adapter types
  final Map<String, RiftSchemaType> types;

  /// Constructor
  const RiftSchema({required this.nextTypeId, required this.types});

  /// From json
  factory RiftSchema.fromJson(Map<String, dynamic> json) =>
      _$RiftSchemaFromJson(json);

  /// To json
  Map<String, dynamic> toJson() => _$RiftSchemaToJson(this);
}

/// Information about a Rift adapter type
@JsonSerializable()
@immutable
class RiftSchemaType {
  /// The adapter's type ID
  final int typeId;

  /// The next field index to use for future updates
  final int nextIndex;

  /// The fields in the adapter
  final Map<String, RiftSchemaField> fields;

  /// Constructor
  const RiftSchemaType({
    required this.typeId,
    required this.nextIndex,
    required this.fields,
  });

  /// From json
  factory RiftSchemaType.fromJson(Map<String, dynamic> json) =>
      _$RiftSchemaTypeFromJson(json);

  /// To json
  Map<String, dynamic> toJson() => _$RiftSchemaTypeToJson(this);

  /// Copy with
  RiftSchemaType copyWith({Map<String, RiftSchemaField>? fields}) {
    return RiftSchemaType(
      typeId: typeId,
      nextIndex: nextIndex,
      fields: fields ?? this.fields,
    );
  }
}

/// Information about a Rift adapter field
@JsonSerializable()
@immutable
class RiftSchemaField {
  /// The field index
  final int index;

  /// Constructor
  const RiftSchemaField({required this.index});

  /// From json
  factory RiftSchemaField.fromJson(Map<String, dynamic> json) =>
      _$RiftSchemaFieldFromJson(json);

  /// To json
  Map<String, dynamic> toJson() => _$RiftSchemaFieldToJson(this);
}
